name: Go CI/CD


on:
    push:
        branches: [ "main" ]

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  go-version: '1.23'

            - name: Go Test
              run: go test ./... -v

            - name: Login to Aliyun Container Registry
              uses: docker/login-action@v3
              with:
                  registry: crpi-kc1xjy517ehrbwcm.cn-shanghai.personal.cr.aliyuncs.com
                  username: ${{ secrets.ALIYUN_USERNAME }}
                  password: ${{ secrets.ALIYUN_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build -t crpi-kc1xjy517ehrbwcm.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/go-cicd-template:latest .

            - name: Push Docker image
              run: |
                  docker push crpi-kc1xjy517ehrbwcm.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/go-cicd-template:latest

            - name: Deploy to Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login crpi-kc1xjy517ehrbwcm.cn-shanghai.personal.cr.aliyuncs.com -u "${{ secrets.ALIYUN_USERNAME }}" --password-stdin
                      
                      docker pull crpi-kc1xjy517ehrbwcm.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/go-cicd-template:latest
                      
                      docker stop go-app 2>/dev/null || true
                      docker rm go-app 2>/dev/null || true
                      
                      docker run -d \
                        --name go-app \
                        -p 8080:8080 \
                        -e APP_ENV=prod \
                        crpi-kc1xjy517ehrbwcm.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/go-cicd-template:latest
                      
                      docker ps | grep go-app
